# Generated by Django 5.2.6 on 2025-09-08 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KsiOidcClientConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.URLField(null=True)),
                ('client_id', models.CharField(null=True)),
                ('client_secret', models.CharField(null=True)),
                ('configuration_endpoint', models.URLField(null=True)),
                ('registration_token', models.CharField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KsiOidcUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ksi_oidc_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sub', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
