# Generated by Django 5.2.6 on 2025-09-07 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_user_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='KsiOidcUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ksi_oidc_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sub', models.CharField(unique=True)),
            ],
        ),
    ]
